### ISSUE TITLE
Consider not broadcasting newly created names

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/mdns-ice-candidates#85]
This won't completely solve the problem of DoS due to excessive PC creation, but it might help.

**Comment by juberti** [comment]
@tQsW mentioned that we should do this, but I didn't see it in the document.

**Comment by youennf** [comment]
As @tQsW pointed out, https://tools.ietf.org/html/rfc6762#section-8 the mDNS spec recommends to do that. It might be good to point that out in the draft.

It makes it cheaper to register names.
If we mandate this, we could also mandate each PC to create its own names.

Current mDNS APIs might not surface this ability though.
Also, there may be side effects (mDNS relays e.g.).

I would tend for now to recommend but not mandate it.

**Comment by juberti** [comment]
Pending a resolution on #84.

**Comment by youennf** [comment]
More thoughts on this issue after discussing with Ted and Stuart:
- Skipping registration or blocking/delaying registration due to excessive registrations have the same impact as long as the MDNS ICE candidate is still provided to the web application: the other party will try to resolve the name by sending an explicit query.
- The spec is not clear whether if probing is delayed or even blocked, MDNS ICE candidate exposure is delayed/blocked. Maybe we should clarify this.
- Except for some increased connection setup, this is probably fine to skip registration. This means that with good enough implementations, and not caring too much about connection setup latency below 300ms, we might be able to consume more names.
- We should probably encourage the querying node to set the unicast-response bit. That way, the registering node will send a response through unicast. This has some benefits as it reduces the MDNS traffic and makes it less obvious that two peers are about to connect.

**Comment by youennf** [comment]
cc @abhayakara

**Comment by youennf** [comment]
Filed https://github.com/rtcweb-wg/mdns-ice-candidates/pull/111
@Abhayakara, could you take a look?

I have a question related to not sending a multicast announcement in case of unicast-response bit set.
It seems to me we this is a nice optimization.
But there might be a risk of a node A not actually sending a query because another node B just did it. In that case, A might never receive any answer if not retrying later on. This is a case that might already happen with mDNS so maybe we have nothing to say about it.

**Comment by Abhayakara** [comment]
The unicast-response bit is sent in discovery probes.   In the scenario you are describing, presumably node B has just send a query with the unicast bit sent.   Node A would have seen that query, but would have seen the unicast bit, and therefore shouldn't be taking the lack of a multicast response as an indication that the target of the query is not present.

Is this the flow you had in mind?

**Comment by youennf** [comment]
Yes, this is the flow I have in mind.
Do we need to write anything about it here or is it a known mDNS pattern?

**Comment by Abhayakara** [comment]
I think that it would be a bug for node A to not send a query in the case you are describing.   However, I don't know for sure that the bug doesn't exist.

**Comment by youennf** [comment]
Closing with https://github.com/rtcweb-wg/mdns-ice-candidates/pull/111
